name: code-coverage
on:
  push:
   branches: [main]
  pull_request:
   branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - name: check code coverage 
        run: npm run coverage 
