name: concurrency workflow level
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.concurrency.yml }}-${{ github.main }}
  cancel-in-progress: true
jobs: 
  test: 
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - name: hello world
       run: echo hello world
       
