name: demo-01
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: runing helloword programe
        run: echo Hello World!
    
