name: Docker push

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r Docker/requirements.txt

      - name: Run Flask app and test response
        run: |
          python Docker/app.py &
          sleep 5
          curl --fail http://localhost:5000 | grep "Hello from Dockerized Flask"

  build-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t vinodm2001/Docker-Action:latest -f Docker/Dockerfile Docker/

      - name: Push Docker image
        run: docker push vinodm2001/Docker-Action:latest
