name: Build and Deploy Node.js 20 Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: nodejs01  # Replace with your Function App name
  RESOURCE_GROUP: ABC                # Replace with your Resource Group
  PACKAGE_PATH: release.zip

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: api/HttpTrigger1
        run: npm install

      - name: Package Function App
        run: |
          zip -r ${{ env.PACKAGE_PATH }} . -x ".git/*" ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-function-app
          path: ${{ env.PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-function-app

      - name: Azure Login (Service Principal)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Function App
        run: |
          az functionapp deployment source config-zip \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
            --src ${{ env.PACKAGE_PATH }}

      - name: Logout from Azure
        run: az logout
