name: Build and Deploy Node.js Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: nodejs01
  RESOURCE_GROUP: ABC
  NODE_VERSION: '20'
  WORKING_DIRECTORY: 'my-node-function-app'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm install

      - name: Build (optional, if applicable)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run build || echo "No build step defined"

      - name: Azure Login (Service Principal)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Function App
        run: |
          az functionapp deployment source config-zip \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
            --src ${{ env.WORKING_DIRECTORY }}.zip

      - name: Logout from Azure
        run: az logout
