name: Build and Deploy to Azure Function App (Python)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies & run tests
        working-directory: my-flask-app1
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          PYTHONPATH=. pytest tests


      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'GH-action'
          package: 'my-flask-app1'  # Folder with host.json
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
