name: Build, Test, and Deploy Python App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dev:
    name: Build in Dev
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: my-flask-app
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    environment: Test
    needs: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: my-flask-app
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        working-directory: my-flask-app
        run: |
          source venv/bin/activate
          pytest

      - name: Package app
        run: |
          cd my-flask-app
          zip -r ../release.zip . -x "venv/*" ".git/*" ".github/*" "__pycache__/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    environment:
      name: Deploy
      url: https://actions.azurewebsites.net
    needs: test

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'actions'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
