name: Node CI (password‑based SSH)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
###############################################################################
# 1️⃣ TEST JOB
###############################################################################
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - run: npm install
      - run: npm test

###############################################################################
# 2️⃣ BUILD JOB
###############################################################################
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - run: npm install --omit=dev
      - run: npm pack
      - uses: actions/upload-artifact@v4
        with:
          name: calculator-tarball
          path: "*.tgz"
          if-no-files-found: error

###############################################################################
# 3️⃣ DEPLOY JOB  (password auth)
###############################################################################
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: calculator-tarball
          path: ./dist

      - run: |
          mkdir -p ./deploy
          tar -xzf ./dist/*.tgz -C ./deploy --strip-components=1
          ls -R ./deploy

      # 1. Install sshpass (for non‑interactive password auth)
      - name: Install sshpass
        run: |
          sudo apt-get update -y
          sudo apt-get install -y sshpass

      # 2. Copy files to Azure VM
      - name: Copy to Azure VM (password auth)
        env:
          SSHPASS: ${{ secrets.AZURE_VM_PASSWORD }}
        run: |
          sshpass -e rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./deploy/ \
            ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }}:${{ secrets.AZURE_VM_PATH }}/

      # 3. Install deps & restart via PM2
      - name: Remote install & restart (password auth)
        env:
          SSHPASS: ${{ secrets.AZURE_VM_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no \
            ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }} <<'EOF'
              cd ${{ secrets.AZURE_VM_PATH }}
              npm install --omit=dev
              pm2 reload calculator || pm2 start app.js --name calculator --time
          EOF
