name: Script
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    name: Shell Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: To list repo files
        run: ls -ltra
      - name: Executing Shell Scripts
        run: |
          chmod 777 Executing_Shell_Scripts.sh
          ./ Executing_Shell_Scripts.sh
          
