name: Jira Login Secrets 
on:
  push:
    branches: ["main"]
jobs:
  login-to-jira:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Jira
        run: |
          echo "Logging in to Jira..."
          curl -u "${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
            -X GET "${{ secrets.JIRA_URL }}/rest/api/3/myself"

