name: Self hosted runners

on:
  push:
    branches: ["main"]

jobs:
  self-hosted-runners:
    runs-on: [self-hosted, X64, Linux]  
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        run: |
          sudo apt update
          sudo apt -y install python3 python3-pip

      - name: Run the Python code
        run: python3 pattren.py
