name: sequential-order
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: uduntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install gcc compliler
        run: |
          sudo apt update
          sudo apt -y install gcc
          gcc main.c -o hello
  test:
    needs: [build]
    runs-on: uduntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: running c code
        run: ./hello
  output:
    needs: [build,test]
    runs-on: uduntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: to print output
        run: echo output
  output-test:
      if: ${{always()}}
      needs: [test]
      runs-on: uduntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: to print output
          run: echo output-test
  
