name: sequential-order
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest  # Fixed typo here
    steps:
      - uses: actions/checkout@v4
      - name: Install GCC Compiler
        run: |
          sudo apt update
          sudo apt -y install gcc
          gcc main.c -o hello

  test:
    needs: [build]
    runs-on: ubuntu-latest  # Fixed typo here
    steps:
      - uses: actions/checkout@v4
      - name: Running C code
        run: ./hello

  output:
    needs: [build, test]
    runs-on: ubuntu-latest  # Fixed typo here
    steps:
      - uses: actions/checkout@v4
      - name: Print output
        run: echo output

  output-test:
    if: ${{ always() }}
    needs: [test]
    runs-on: ubuntu-latest  # Fixed typo here
    steps:
      - uses: actions/checkout@v4
      - name: Print output-test
        run: echo output-test
