name: Storing workflow data and report to AWS S3

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    name: Run code and store outputs

    steps:
      - uses: actions/checkout@v4

      - name: Install Python (if needed) and run script twice
        run: |
          sudo apt update
          sudo apt -y install python3 python3-pip
          # ► Run once and save to output1.log
          python3 pattren.py > output1.log
          # ► Run again and save to output2.log
          python3 pattren.py --mode=second-run > output2.log

      - name: Upload output1 to artifact
        uses: actions/upload-artifact@v4
        with:
          name: output1
          path: output1.log

      - name: Upload output2 to artifact
        uses: actions/upload-artifact@v4
        with:
          name: output2
          path: output2.log


  output:
    needs: build
    runs-on: ubuntu-latest
    name: Show output1

    steps:
      - name: Download output1 artifact
        uses: actions/download-artifact@v4
        with:
          name: output1

      - name: Display output1
        run: cat output1.log


  success:
    needs: build
    runs-on: ubuntu-latest
    name: Verify build completed

    steps:
      - name: Success
        run: echo "Build completed successfully."


  reports-s3:
    needs: build
    runs-on: ubuntu-latest
    name: AWS S3 – Upload Reports
    continue-on-error: true

    steps:
      - name: Download output1 artifact
        uses: actions/download-artifact@v4
        with:
          name: output1

      - name: Download output2 artifact
        uses: actions/download-artifact@v4
        with:
          name: output2

      - name: Merge log files
        run: |
          set -e
          mkdir "reports-${{ github.sha }}"
          mv output1.log "reports-${{ github.sha }}/"
          mv output2.log "reports-${{ github.sha }}/"
          ls -ltr "reports-${{ github.sha }}"

      - name: Upload to AWS S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: github-reports2001
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          SOURCE_DIR: reports-${{ github.sha }}
          DEST_DIR: reports-${{ github.sha }}
