name: Storing workflow data 
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    name: To run code and store a output in a file 
   
    steps:
      - uses: actions/checkout@v4
      - name: To Run the code
        run: |
             sudo apt update
             sudo apt -y install python3
             sudo apt -y install python3-pip
             python3 pattren.py > output.log
      - name: Upload store data to the artifact
      - uses: actions/upload-artifact@v4
        with: 
          name: output
          path: output.log
  output:
    needs: [build]
    runs-on: ubuntu-latest
    name: To dowanload uploaded artifacts
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download@v4
        with:
          name: output
      - name: Displaying output file
        run: cat output
  success:
    needs: [build,output]
    runs-on: ubuntu-latest
    name: to check build and output job is running with out issues
    
    steps:
      - uses: actions/checkout@v4
      - name: success
    
          
