name: workflow filters and activities

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]
    branches:
      - main
    paths-ignore:
      - README.md        # root file
      - "**/README.md"   # README anywhere
      - "**/*.md"        # any markdown file

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo hello world
